/-
Copyright (c) 2026 The Flypitch Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

Erdős #501 (first question) holds after collapsing 𝔠 to ω₁ and adding ω₂ random reals: statement.
-/
import Mathlib.Topology.Order.UpperLowerSetTopology
import Mathlib.Analysis.Real.Cardinality
import Flypitch4.Erdos501.Sentence
import Flypitch4.RandomAlgebra
import Flypitch4.ForcingCH

/-!
# `Col(ω₁, ℝ) ∗ (ω₂ random reals)` forces a positive answer to Erdős #501 — the statement

This file states (and leaves as `sorry`) the assertion

> *After forcing with `Col(ω₁, ℝ)` (which makes `CH` true) and then adding `ω₂` random reals,
> the first question of Erdős problem #501 has a positive answer*, i.e. the proposition
> formalized as `erdos_501` in DeepMind's `formal-conjectures` (rendered as the `L_ZFC`-sentence
> `Erdos501_f`, see `Sentence.lean`) holds in the resulting model of `ZFC`.

It is stated in the Boolean-valued-model framework of Flypitch: for the complete Boolean
algebra `𝔹_col_random` of the two-step forcing, the Boolean-valued model `V 𝔹_col_random` of
`ZFC` (`bSet_models_ZFC`) satisfies `Erdos501_f` with Boolean value `⊤`.

## The forcing notion

* **First step, `Col(ω₁, ℝ)`.**  This is Flypitch's `collapse_algebra.𝔹_collapse`, the regular
  open algebra of the space of functions `ℵ₁ → 𝒫(ω)` with the topology generated by the
  conditions of `Fn(ω₁, 𝒫(ω), <ω₁)` (countable partial functions), i.e. the Boolean completion of
  the Lévy collapse `Col(ω₁, 𝒫(ω))`; any bijection `ℝ ≃ 𝒫(ω)` identifies it with `Col(ω₁, ℝ)`.
  Flypitch proves `⊤ ⊩[V 𝔹_collapse] CH_f` (`collapse_algebra.CH_true`).
* **Second step, `ω₂` random reals.**  In the collapse extension `V[G]`, `ω₂^{V[G]} = (𝔠⁺)^V`
  (all cardinals in `(ω₁, 𝔠]` are collapsed, `𝔠⁺` is preserved since `|Col(ω₁, ℝ)| = 𝔠`), and the
  `ω₂`-random algebra *of `V[G]`*, i.e. the measure algebra of `2^(ω₂^{V[G]} × ω)` computed in
  `V[G]`, coincides with the ground-model measure algebra `randomAlgebra RandomIndex` with
  `#RandomIndex = 𝔠⁺`: `Col(ω₁, ℝ)` is σ-closed, so `V[G]` has no new reals and no new countable
  sequences of ordinals, hence no new Borel codes, and the measure algebra is ccc.  Consequently
  the two-step iteration `𝔹_collapse ∗ (ω₂-random algebra)˙` is the iteration with the *check
  name* of `randomAlgebra RandomIndex`, whose forcing poset is (densely) the **product poset**
  `𝔹_collapse⁺ × (randomAlgebra RandomIndex)⁺`.
* `𝔹_col_random` is the Boolean completion (regular open algebra) of that product poset.

The identification of the second step with a ground-model algebra is a (standard) theorem
about the specific forcing `Col(ω₁, ℝ)`, and it is used here in the *definition* of the forcing
notion; a formalization of general two-step iterations `𝔹 ∗ Ċ` with names for Boolean algebras
inside `V 𝔹` would allow stating the assertion with the random algebra computed inside
`V 𝔹_collapse` instead.
-/

open Fol bSet collapse_algebra Flypitch
open scoped Cardinal

namespace Flypitch.Erdos501

/-! ### Boolean completions of posets -/

/-- The nonzero elements of a Boolean algebra `𝔹`, ordered by `≤`: the forcing poset of `𝔹`
(`p ≤ q` means that `p` is stronger than `q`). -/
abbrev Pos (𝔹 : Type) [BooleanAlgebra 𝔹] : Type := {b : 𝔹 // ⊥ < b}

instance Pos.instNonempty (𝔹 : Type) [NontrivialCompleteBooleanAlgebra 𝔹] : Nonempty (Pos 𝔹) :=
  ⟨⟨⊤, nontrivial_bot_lt_top⟩⟩

/-- The Boolean completion `RO(P)` of a poset `P`: the regular open algebra of `P` with the
topology whose open sets are the lower sets (basic open sets `↓p = {q | q ≤ p}`).  For a
separative poset this is the complete Boolean algebra into which `P` embeds densely. -/
abbrev BooleanCompletion (P : Type) [Preorder P] : Type :=
  Flypitch.RegularOpens (Topology.WithLowerSet P)

noncomputable instance BooleanCompletion.instNontrivialCBA (P : Type) [Preorder P] [Nonempty P] :
    NontrivialCompleteBooleanAlgebra (BooleanCompletion P) :=
  Flypitch.RegularOpens.instNontrivialCBA

/-! ### The forcing `Col(ω₁, ℝ) ∗ (ω₂ random reals)` -/

/-- The index set of the random reals: a set of cardinality `𝔠⁺ = (2^ℵ₀)⁺`, which is `ω₂` of the
extension by `Col(ω₁, ℝ)`. -/
abbrev RandomIndex : Type := (PSet.card_ex (Order.succ Cardinal.continuum)).Type

lemma mk_RandomIndex : #RandomIndex = Order.succ Cardinal.continuum :=
  @PSet.mk_type_mk_eq'' _ (Cardinal.aleph0_le_continuum.trans (Order.le_succ _))

/-- The random algebra of the second step: `𝔠⁺` (= `ω₂` of the collapse extension) random
reals. -/
abbrev 𝔹_random_succ_continuum : Type := randomAlgebra RandomIndex

/-- The complete Boolean algebra of the two-step forcing "`Col(ω₁, ℝ)`, then `ω₂` random reals":
the Boolean completion of the product poset `𝔹_collapse⁺ × 𝔹_random_succ_continuum⁺`. -/
noncomputable def 𝔹_col_random : Type :=
  BooleanCompletion (Pos 𝔹_collapse × Pos 𝔹_random_succ_continuum)

noncomputable instance 𝔹_col_random.instNontrivialCBA :
    NontrivialCompleteBooleanAlgebra 𝔹_col_random :=
  BooleanCompletion.instNontrivialCBA _

/-! ### The assertion -/

/-- **Erdős #501 (first question) after `Col(ω₁, ℝ)` and `ω₂` random reals.**

In the Boolean-valued model `V 𝔹_col_random` of `ZFC` — the model obtained by first collapsing
the continuum to `ω₁` and then adding `ω₂` random reals — the sentence `Erdos501_f` (the
`L_ZFC`-rendering of DeepMind's `erdos_501`: every family `⟨A_x : x ∈ ℝ⟩` of bounded sets of
reals of outer measure `< 1` has an infinite independent set) has Boolean value `⊤`. -/
theorem erdos501_of_col_random : ⊤ ⊩[V 𝔹_col_random] Erdos501_f := by
  sorry

/-- The model `V 𝔹_col_random` is a Boolean-valued model of `ZFC` (Flypitch's fundamental
theorem of forcing), so the assertion is about a model of `ZFC`. -/
theorem V_col_random_models_ZFC : ⊤ ⊩ₜ[V 𝔹_col_random] ZFC :=
  bSet_models_ZFC

/-- Consequence of the assertion: `ZFC` does not refute the Erdős property, i.e. a positive
answer to Erdős #501 (first question) is relatively consistent with `ZFC`.  (The formalized route
to this consequence goes through the random algebra alone: see `Main.lean`,
`neg_Erdos501_ex_f_unprovable` (proved) and `neg_Erdos501_f_unprovable`.) -/
theorem neg_Erdos501_f_unprovable_of_col_random :
    ¬ (ZFC ⊢ₛ' (bd_not Erdos501_f : sentence L_ZFC)) := by
  apply unprovable_of_model_neg (V 𝔹_col_random) bSet_models_ZFC nontrivial_bot_lt_top
  rw [forced_in_not]
  exact erdos501_of_col_random

end Flypitch.Erdos501
